# Generated by Django 5.0.4 on 2024-04-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_globalsearch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalSearch',
        ),
    ]
